//! Embeds the bundled DSL rule packs (`rules/dsl/**/*.json`) into the crate at compile time, so a
//! native host binary is fully self-contained — no sidecar `rules/` directory to distribute, misplace,
//! or silently lose (a missing pack directory would degrade to "0 DSL rules" with only a warning).
//! Generates `$OUT_DIR/bundled_packs.rs` holding one `include_str!` entry per pack file, sorted by
//! relative path so the embedded order (and therefore pack load order) is deterministic.

use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dsl_dir = manifest_dir.join("../../rules/dsl");
    let mut entries: Vec<(String, String)> = Vec::new();
    collect(&dsl_dir, &dsl_dir, &mut entries);
    entries.sort();

    let mut out = String::from(
        "/// Generated by build.rs — `(relative path under rules/dsl, pack JSON source)`, sorted by\n\
         /// relative path for deterministic load order.\n\
         pub static BUNDLED_PACK_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (rel, abs) in &entries {
        out.push_str(&format!("    ({rel:?}, include_str!({abs:?})),\n"));
    }
    out.push_str("];\n");

    out.push_str(&example_pack_contracts(&manifest_dir));

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bundled_packs.rs");
    std::fs::write(&out_path, out).expect("write bundled_packs.rs");
}

/// The EXPORTED packs — `examples/packs/*.json`, shipped in the repository but deliberately NOT
/// bundled — emitted as ready-made contract-resource rows.
///
/// # Why they are baked at all
///
/// A rule moved out of the bundle is still real, and until 2026-08-12 there was no way to GET it from
/// a shipped artifact: measured that week, the release carried 18 assets and not one `.json` pack, the
/// `.mcpb` zip payload had none, and npm's `files:` list had none either. So the repository's own
/// advice — "copy the pack back if you want those rules" — began with a step that only worked from a
/// source checkout. Baking them turns step one from a 404 into a resource every host already serves.
///
/// # Why the ROWS are generated here and not hand-written in `crates/summary/src/contracts.rs`
///
/// One row per pack, written by hand, is a list that goes stale the day the next pack is exported —
/// and exporting more packs is the standing plan, which makes it a list guaranteed to rot. The
/// derivation is the same walk the bundled packs already get, one directory over. `ContractDoc`'s
/// fields are `&'static str`, so the NAME and DESCRIPTION are emitted as literals here rather than
/// formatted at run time: that keeps the table free of leaked allocations, and the only per-pack
/// variable is the file stem.
///
/// # Why the served bytes are STAMPED and the committed file is not
///
/// The served copy carries an `exported_from` object naming this build's version and the resource it
/// came out of (`zzop_core::dsl::def::PackExport` is the reading end). Stamping the COMMITTED
/// `examples/packs/*.json` instead was rejected on two counts. First, a version written into a tracked
/// file is a value a human has to re-type every release, and `examples/` is explicitly outside
/// `scripts/check-release-version-propagation.sh`'s subject, so nothing would catch it going stale —
/// a staleness beacon that itself goes stale. Second, the fact worth recording is not "which release
/// was current when someone last edited this file", it is "which build handed you these bytes", and
/// only the retrieval moment knows that. Stamping here answers the second question and needs no
/// maintenance: `CARGO_PKG_VERSION` is the `[workspace.package] version` in Cargo.toml, the repo's
/// version SSOT. A commit SHA was not used and must not be — regeneration always precedes the commit
/// that carries it, so such a stamp permanently names the commit before its own (this repo has now
/// paid for that shape twice: `00cf60b`, `84747d7`).
///
/// The injection is TEXTUAL — the stamp is spliced in right after the opening brace and the rest of
/// the file is passed through byte for byte. Round-tripping through a JSON parser would reorder keys
/// and reflow the formatting of a file whose whole purpose is to be saved and then read by a human.
fn example_pack_contracts(manifest_dir: &Path) -> String {
    let dir = manifest_dir.join("../../examples/packs");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut rows: Vec<(String, String)> = Vec::new();
    if let Ok(read) = std::fs::read_dir(&dir) {
        for entry in read.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("example pack file stem")
                .to_string();
            rows.push((stem, path.to_string_lossy().into_owned()));
        }
    }
    rows.sort();

    let version = std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION is always set");

    let mut out = String::from(
        "/// Generated by build.rs — `(contract-resource name, description, pack JSON source)` for every\n\
         /// `examples/packs/*.json`, sorted by file stem. The source is the committed file's bytes with\n\
         /// one `exported_from` retrieval stamp spliced in; see build.rs for why these are baked and why\n\
         /// the stamp lives here rather than in the committed file.\n\
         pub static EXAMPLE_PACK_CONTRACTS: &[(&str, &str, &str)] = &[\n",
    );
    for (stem, abs) in &rows {
        let name = format!("example-pack-{stem}");
        let description = format!(
            "The `{stem}` example rule pack — shipped in this binary but NOT loaded: its rules run \
             only when a config points at them. This is the RETRIEVAL path for rules exported out of \
             the bundle; `rule-catalog` documents these ids too, under its `Exported packs` heading, \
             so finding one there means it is DOCUMENTED, never that this run loaded it. Save these \
             exact bytes as `{stem}.json` under `<tree>/zzop/rules/` (which needs no config at all), \
             or in any directory named by `packs.extraDirs` — that key REPLACES the `zzop/rules/` \
             default rather than adding to it, so a tree already using it must name this directory \
             too. The pack's own `id` and its rules' ids are what `rules`/`disabledRules`, severity \
             overrides and `zzop-<rule>-ok` markers then match on."
        );
        let stamped = stamp_pack(abs, &name, &version);
        out.push_str(&format!("    ({name:?}, {description:?}, {stamped:?}),\n"));
    }
    out.push_str("];\n");
    out
}

/// The committed pack's bytes with one `exported_from` object spliced in after the opening brace —
/// see [`example_pack_contracts`] for why the stamp is minted here instead of being written into the
/// file. Everything after that first brace, including the file's formatting and key order, is passed
/// through unchanged, so the bytes a reader saves differ from the repository file by exactly the one
/// line they can see.
///
/// Panics rather than degrading if the file is not an object with at least one key. A silent fallback
/// to unstamped bytes would put the whole detection lane back where it started while every test that
/// only asks "does this parse" stayed green.
fn stamp_pack(path: &str, contract_name: &str, version: &str) -> String {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let rest = text
        .strip_prefix('{')
        .unwrap_or_else(|| panic!("{path} must be a JSON object — it does not open with a brace"));
    assert!(
        rest.trim_start().starts_with('"'),
        "{path} opens with no key after its brace — splicing a stamp in would produce invalid JSON"
    );
    // The file's OWN line terminator, read off the byte after the brace rather than assumed: this repo
    // is developed on a CRLF checkout and built on an LF one, and a hard-coded "\n" would emit a file
    // with one alien line ending in it on whichever side guessed wrong.
    let newline = if rest.starts_with("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    format!(
        "{{{newline}  \"exported_from\": {{ \"zzop_version\": \"{version}\", \"contract\": \"{contract_name}\" }},{rest}"
    )
}

fn collect(base: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    println!("cargo:rerun-if-changed={}", dir.display());
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, entries);
        } else if path.extension().and_then(|e| e.to_str()) == Some("json") {
            println!("cargo:rerun-if-changed={}", path.display());
            let rel = path
                .strip_prefix(base)
                .expect("pack path under rules/dsl")
                .to_string_lossy()
                .replace('\\', "/");
            entries.push((rel, path.to_string_lossy().into_owned()));
        }
    }
}
