//! Embeds the bundled DSL rule packs (`rules/dsl/**/*.json`) into the crate at compile time, so a
//! native host binary is fully self-contained — no sidecar `rules/` directory to distribute, misplace,
//! or silently lose (a missing pack directory would degrade to "0 DSL rules" with only a warning).
//! Generates `$OUT_DIR/bundled_packs.rs` holding one `include_str!` entry per pack file, sorted by
//! relative path so the embedded order (and therefore pack load order) is deterministic.

use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dsl_dir = manifest_dir.join("../../rules/dsl");
    let mut entries: Vec<(String, String)> = Vec::new();
    collect(&dsl_dir, &dsl_dir, &mut entries);
    entries.sort();

    let mut out = String::from(
        "/// Generated by build.rs — `(relative path under rules/dsl, pack JSON source)`, sorted by\n\
         /// relative path for deterministic load order.\n\
         pub static BUNDLED_PACK_SOURCES: &[(&str, &str)] = &[\n",
    );
    for (rel, abs) in &entries {
        out.push_str(&format!("    ({rel:?}, include_str!({abs:?})),\n"));
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bundled_packs.rs");
    std::fs::write(&out_path, out).expect("write bundled_packs.rs");
}

fn collect(base: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    println!("cargo:rerun-if-changed={}", dir.display());
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, entries);
        } else if path.extension().and_then(|e| e.to_str()) == Some("json") {
            println!("cargo:rerun-if-changed={}", path.display());
            let rel = path
                .strip_prefix(base)
                .expect("pack path under rules/dsl")
                .to_string_lossy()
                .replace('\\', "/");
            entries.push((rel, path.to_string_lossy().into_owned()));
        }
    }
}
