//! Which `vocabulary.*` keys are compared against a NORMALIZED input, and by which transform.
//!
//! ## What this table is for
//! Most vocabulary keys are compared verbatim, so any spelling a user declares can match something. A
//! few are not: the consuming rule normalizes the input name first and then looks the result up in the
//! declared list. For those, a declared entry that does not survive the same normalization **can never
//! match anything, ever** — and until 2026-08-05 that was completely silent. Declaring
//! `sensitiveResponseFieldExactNames: ["sessionToken"]` switched a protection ON in the user's mind and
//! left it OFF in the engine, with no warning on any lane.
//!
//! `zzop-config` reads this table at config-load time and warns per offending entry. The transforms
//! themselves are `zzop_core::vocab_norm`'s, which the consuming rules call too — so the warning and the
//! comparison cannot drift apart (see that module's doc for why the kernel is the right home).
//!
//! ## Why a table rather than one normalizer for everything
//! A blanket normalization would be WRONG, and measurably so: `secretParamNames` legitimately carries
//! both `api_key` and `api-key` because a URL query parameter can be spelled either way, and the shipped
//! built-in list has both. Folding separators there would merge two real declarations into one. So each
//! key names its own transform and the ones absent from this table are compared verbatim.
//!
//! ## Adding a key
//! If a new rule normalizes its input before a vocabulary lookup, add the key here in the same change.
//! Nothing can detect that omission for you — the cost of forgetting is exactly the silent failure above,
//! which is why the consuming rules were rewired to call the shared transform rather than a local copy:
//! a reader of the rule now lands on `vocab_norm`, whose module doc names this table.

/// A config-key spelling paired with the transform its consuming rule applies to the INPUT before
/// comparing against the declared list. Camel-case spellings, matching the config file surface — this is
/// read by a front end that has the raw JSON, not the deserialized struct.
pub type NormalizedKey = (&'static str, fn(&str) -> String);

/// Every `vocabulary.*` key whose declared entries are matched against a normalized input.
///
/// Keys NOT listed here are compared verbatim and need no check. That is the common case, and it is why
/// this list is short rather than a mirror of the whole struct.
pub const NORMALIZED_VOCABULARY_KEYS: &[NormalizedKey] = &[
    // `external-secret-in-url` lowercases the query-parameter name it reads out of a URL.
    (
        "secretParamNames",
        zzop_core::vocab_norm::ascii_lowercase as fn(&str) -> String,
    ),
    // The router-mount idempotency probe lowercases the header literal it finds in a handler body. The
    // HTTP convention spelling is `Idempotency-Key`, so this is the key a user is MOST likely to declare
    // in a form that cannot match — the reason it is worth warning about rather than documenting.
    (
        "idempotencyHeaderNames",
        zzop_core::vocab_norm::ascii_lowercase,
    ),
    // `float-money` lowercases the schema field name before the substring test.
    ("moneyTokens", zzop_core::vocab_norm::ascii_lowercase),
    // `sensitive-response-field`'s three axes share one normalized name: lowercase AND separators
    // dropped, so a declared `password_hash` cannot match either.
    (
        "sensitiveResponseFieldSubstrings",
        zzop_core::vocab_norm::unicode_lowercase_without_separators,
    ),
    (
        "sensitiveResponseFieldExactNames",
        zzop_core::vocab_norm::unicode_lowercase_without_separators,
    ),
    (
        "sensitiveResponseFieldSuffixes",
        zzop_core::vocab_norm::unicode_lowercase_without_separators,
    ),
    // `has_generated_banner` lowercases the comment body before the substring test — so a marker
    // declared with a capital letter (the `AUTO-GENERATED BY …` spelling a generator actually emits)
    // can never match. `docs/extending.md` shipped exactly that spelling as its example.
    (
        "generatedFileMarkers",
        zzop_core::vocab_norm::ascii_lowercase,
    ),
    // The Python guard-name producer folds the callable's name — Unicode lowercase with `_` dropped —
    // before every one of these four lookups (`adapters::guard_vocab::is_guard_name`). A declared
    // `require_login` therefore never matches; `requirelogin` does.
    (
        "pythonGuardSubstrings",
        zzop_core::vocab_norm::unicode_lowercase_without_separators,
    ),
    (
        "pythonGuardAnonymousVetoSubstrings",
        zzop_core::vocab_norm::unicode_lowercase_without_separators,
    ),
    (
        "pythonGuardReportVetoPrefixes",
        zzop_core::vocab_norm::unicode_lowercase_without_separators,
    ),
    (
        "pythonGuardReportVetoSuffixes",
        zzop_core::vocab_norm::unicode_lowercase_without_separators,
    ),
    // The TypeScript router-mount guard judges an identifier TAIL that `name_tail` has already
    // lowercased (`adapters::router_mounts::guard`). Separators survive there, unlike the Python
    // sibling above — the two producers fold differently and this table is where that is visible.
    (
        "routerNameVetoSuffixes",
        zzop_core::vocab_norm::ascii_lowercase,
    ),
    (
        "envAxisVetoSubstrings",
        zzop_core::vocab_norm::ascii_lowercase,
    ),
    (
        "wrapperGuardPrefixes",
        zzop_core::vocab_norm::ascii_lowercase,
    ),
    // `mutating-route-no-auth` lowercases each camel-case word of the qualifier before the lookup
    // (`mutating_route_no_auth::qualifier::tokens_are_guard`).
    (
        "authGuardQualifierTokens",
        zzop_core::vocab_norm::ascii_lowercase,
    ),
    // NOT listed, and the omission is a judgment rather than an oversight: `rustOptionalExtractorPrefixes`
    // folds BOTH sides (`lang::extractor_guards` lowercases the declared prefix too), so a capitalized
    // entry there matches fine and listing it would warn about a declaration that works.
];

/// The transform for one config key, or `None` when that key is compared verbatim.
pub fn normalizer_for(key: &str) -> Option<fn(&str) -> String> {
    NORMALIZED_VOCABULARY_KEYS
        .iter()
        .find(|(k, _)| *k == key)
        .map(|(_, f)| *f)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::VocabularyConfig;

    #[test]
    fn every_listed_key_is_a_real_vocabulary_key() {
        // A typo here would silently check nothing — the same class of failure the table exists to
        // close, one layer up. The authority is the struct's own serde surface rather than a second
        // reading of `config-surface.json`: `VocabularyConfig` IS the shape being validated, so a key
        // renamed on the struct breaks this test in the same commit that renames it.
        let json = serde_json::to_value(VocabularyConfig::default()).expect("serializes");
        let object = json.as_object().expect("VocabularyConfig is an object");
        for (key, _) in NORMALIZED_VOCABULARY_KEYS {
            assert!(
                object.contains_key(*key),
                "{key} is not a field of VocabularyConfig; known: {:?}",
                object.keys().collect::<Vec<_>>()
            );
        }
    }

    #[test]
    fn the_shipped_built_in_values_all_survive_their_own_normalizer() {
        // `zzop init` writes the built-ins into the user's file. If any of them could not survive its
        // own key's normalization, running `init` would immediately produce the very warning this table
        // powers — a tool warning about the file it just wrote. This is the assertion that makes the
        // warning trustworthy rather than noise.
        let json = serde_json::to_value(VocabularyConfig::built_in())
            .expect("VocabularyConfig serializes");
        for (key, normalize) in NORMALIZED_VOCABULARY_KEYS {
            let Some(entries) = json.get(key).and_then(serde_json::Value::as_array) else {
                continue;
            };
            for entry in entries.iter().filter_map(serde_json::Value::as_str) {
                assert_eq!(
                    normalize(entry),
                    entry,
                    "built-in {key} entry {entry:?} cannot match its own normalized input"
                );
            }
        }
    }

    #[test]
    fn an_unlisted_key_reports_no_normalizer() {
        assert!(normalizer_for("javaSourceRoot").is_none());
        assert!(normalizer_for("secretParamNames").is_some());
    }
}
