//! The generated-file exemption on `egress/get-and-body`: the rule carries a
//! `MethodScan::require_file_absent` banner regex, so a file the author declared machine-generated goes
//! silent. Its fix advice is "use POST (or another body-bearing method), or move the data to query
//! params", which nobody can follow in a file the next `swagger-typescript-api` / `openapi-generator`
//! run overwrites -- measured on the dogfood corpus at 1 finding, on `fe-vue/src/services/api.ts` (a
//! swagger-typescript-api client), which was this rule's ENTIRE yield over the 17-tree corpus.
//!
//! ## What these tests pin, and why each case exists
//! The regex is byte-identical to the one `typescript/as-cast` and `typescript/no-explicit-any` carry,
//! and all three mirror `zzop_engine::generated_banner`'s detector rather than merely containing the
//! marker words, because those layers answer the SAME question about the SAME file and a divergence
//! between them is invisible: `unimported-export` would call a file generated while `get-and-body` did
//! not. So the head window (8 lines) and the comment-prefix requirement are both pinned here, in both
//! directions -- a marker one line past the window, and a marker in a head STRING literal, must each
//! still leave the rule firing. Measured, not asserted: swapping this regex for the loose "marker
//! anywhere in the file" spelling leaves every suppression case below green and reddens exactly the
//! live-file ones -- the three shapes in `a_marker_outside_a_head_comment_does_not_exempt` and the
//! past-the-window half of `the_head_window_ends_at_line_eight`. That is the whole point of having them.
//!
//! ## The disclosure, pinned as a test
//! `vocabulary.generatedFileMarkers` does NOT reach this rule -- a matcher's patterns are compiled from
//! the pack JSON and `zzop-core`'s DSL layer is vocabulary-free by construction, method-scan exactly as
//! much as line-scan. A house generator stamping its own banner is still flagged, and the answer for it
//! is `exclude`. That limitation is stated in the rule's `message`, and the last test below is what
//! stops a future message rewrite from dropping it silently.

use super::*;

/// The offending shape, identical in every fixture below so a count is directly comparable across
/// cases: one function whose span holds a value-position `method: 'GET'` and a `body:`, which is
/// exactly one `get-and-body` finding (anchored on the `body:` trigger line).
const OFFENDING_BODY: &str = "export function load(url: string, data: unknown) {\n  return fetch(url, {\n    method: 'GET',\n    body: JSON.stringify(data),\n  });\n}\n";

/// Tree-relative paths of every `egress/get-and-body` finding over `files`.
fn hit_files(files: &[(&str, &str)]) -> Vec<String> {
    let dir = TempDir::new("zzop-egress-banner");
    for (rel, body) in files {
        dir.write(rel, body);
    }
    let out = scan(&dir);
    hits(&out, "get-and-body")
        .iter()
        .map(|f| f.file.clone())
        .collect()
}

fn count(files: &[(&str, &str)]) -> usize {
    hit_files(files).len()
}

/// A head banner silences the rule WHOLE-FILE -- and the same run's un-bannered sibling still fires, so
/// a zero here cannot be the fixture, the pack load, or the analyzer having done nothing.
#[test]
fn head_banner_silences_the_rule_while_a_sibling_still_fires() {
    let bannered = format!("// @generated by acme-codegen\n{OFFENDING_BODY}");
    let plain = format!("// hand-written, no banner\n{OFFENDING_BODY}");
    let found = hit_files(&[
        ("src/gen.ts", bannered.as_str()),
        ("src/hand.ts", plain.as_str()),
    ]);
    assert!(
        !found.iter().any(|f| f.ends_with("gen.ts")),
        "egress/get-and-body fired on the bannered file: {found:?}"
    );
    assert!(
        found.iter().any(|f| f.ends_with("hand.ts")),
        "egress/get-and-body fired on NEITHER file -- the control is silent too, so the suppression \
         above proves nothing"
    );
}

/// The engine's `MARKERS` list, READ FROM ITS SOURCE BYTES rather than re-typed here.
///
/// `zzop_engine::generated_banner::MARKERS` is `pub(crate)`, so this crate cannot import it — and a
/// hand-copied list is exactly the failure this whole module exists to prevent: add a ninth spelling to
/// the engine and a re-typed list stays green while the layers start disagreeing about which files are
/// generated. Reading the other side's bytes is this repo's established answer when a boundary admits
/// no shared symbol (`rules-http`'s `MARKER_WINDOW_PROSE_PAGES`, the engine's own `surface_parity`
/// source-scrape, and the sibling `rules/dsl/typescript/generated_banner_exemption.rs` all do the same).
///
/// The floor matters: if the const is renamed or reshaped, the extraction yields nothing, and an empty
/// list would make the loop below pass vacuously. So an implausibly small result is a failure.
fn engine_marker_spellings() -> Vec<String> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        // `CARGO_MANIFEST_DIR` is the CRATE root (`rules/`), not this file's directory.
        .join("../crates/engine/src/generated_banner.rs");
    let src = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let body = src
        .split_once("const MARKERS: &[&str] = &[")
        .unwrap_or_else(|| {
            panic!("generated_banner.rs no longer declares `MARKERS` in the shape this pin reads")
        })
        .1;
    let body = body
        .split_once("];")
        .expect("the MARKERS literal is unterminated")
        .0;
    let markers: Vec<String> = body
        .lines()
        .filter_map(|l| l.trim().strip_prefix('"'))
        .filter_map(|l| l.split_once('"').map(|(m, _)| m.to_string()))
        .collect();
    assert!(
        markers.len() >= 5,
        "extracted only {} marker spellings from generated_banner.rs -- the const's shape changed and \
         this pin is now reading almost nothing. An empty list would silence every case below.",
        markers.len()
    );
    markers
}

/// Every banner spelling the engine recognizes must silence this rule too, or the two layers disagree
/// about which files are generated. The spellings come from `engine_marker_spellings()`; the extra heads
/// below are SHAPES, not vocabulary — the real corpus banners in their real casing and comment styles
/// (swagger-typescript-api's uppercase block-comment continuation, which is the fe-vue file this rule
/// was measured on, and the preamble shape that pushes a banner down to line 7).
#[test]
fn every_engine_marker_spelling_is_honored() {
    let mut heads: Vec<String> = engine_marker_spellings()
        .iter()
        .map(|m| format!("// {m}"))
        .collect();
    heads.extend(
        [
            "// This file is auto-generated by @hey-api/openapi-ts",
            "// This file was automatically generated by TanStack Router.",
            "// Code generated by protoc-gen-go. DO NOT EDIT.",
            "/*\n * ## THIS FILE WAS GENERATED VIA SWAGGER-TYPESCRIPT-API ##\n */",
            // Not on line 1, and behind the eslint/ts-nocheck preamble every generator emits.
            "/* eslint-disable */\n\n// @ts-nocheck\n\n// noinspection JSUnusedGlobalSymbols\n\n// @generated",
        ]
        .map(String::from),
    );
    for head in heads {
        let src = format!("{head}\n{OFFENDING_BODY}");
        assert_eq!(
            count(&[("src/gen.ts", src.as_str())]),
            0,
            "banner head not honored:\n{head}"
        );
    }
}

/// The head window is 8 LINES, the same as the engine detector's. Pinned on both sides of the edge so
/// widening it to the whole file (which would silence a hand-written client that merely mentions a
/// generator in a comment) fails here rather than in a user's silent report.
#[test]
fn the_head_window_ends_at_line_eight() {
    let filler = "// 1\n// 2\n// 3\n// 4\n// 5\n// 6\n// 7\n";
    let on_line_eight = format!("{filler}// @generated\n{OFFENDING_BODY}");
    let on_line_nine = format!("{filler}// 8\n// @generated\n{OFFENDING_BODY}");

    assert_eq!(
        count(&[("src/gen.ts", on_line_eight.as_str())]),
        0,
        "a banner on line 8 is inside the head window and must silence the rule"
    );
    assert_eq!(
        count(&[("src/late.ts", on_line_nine.as_str())]),
        1,
        "a banner on line 9 is PAST the head window -- the file is hand-written as far as this \
         exemption is concerned and the rule must still fire"
    );
}

/// A marker must be in a COMMENT, exactly as the engine detector requires. The two live-code shapes that
/// carry marker words in real trees are a string literal (a codegen tool written in TypeScript has its
/// own banner as a template) and a TS private field, whose `#` opens live code.
#[test]
fn a_marker_outside_a_head_comment_does_not_exempt() {
    let in_string =
        format!("export const banner = \"// @generated by our codegen\";\n{OFFENDING_BODY}");
    let in_field = format!("class C {{\n  #autogeneratedId = 1;\n}}\n{OFFENDING_BODY}");
    // Marker on line 11, well past the 8-line head window: the shape of a hand-written client that
    // merely mentions a generator somewhere in its own body.
    let filler = "export const p1 = 1;\nexport const p2 = 2;\nexport const p3 = 3;\nexport const p4 = 4;\nexport const p5 = 5;\nexport const p6 = 6;\nexport const p7 = 7;\nexport const p8 = 8;\nexport const p9 = 9;\n";
    let deep = format!(
        "// ordinary header\n{filler}// auto-generated section below, keep in sync\n{OFFENDING_BODY}"
    );

    for (label, src) in [
        ("head string literal", in_string.as_str()),
        ("TS private field", in_field.as_str()),
        ("comment below the head", deep.as_str()),
    ] {
        assert_eq!(
            count(&[("src/live.ts", src)]),
            1,
            "{label}: file must stay live"
        );
    }
}

/// The exemption's own honesty check. `vocabulary.generatedFileMarkers` is a real config key that the
/// engine's dead-code analyses read and this rule CANNOT (a DSL matcher compiles its patterns from the
/// pack JSON, with no vocabulary input), so a project whose house generator stamps a different banner —
/// or stamps none at all — still gets flagged here. Silence about that reaches the user AS silence, which is why it is in the
/// shipped message and why this test refuses a message that stops saying it.
#[test]
fn disclosure_survives_in_the_message() {
    let pack = egress_pack();
    let rule = pack
        .rules
        .iter()
        .find(|r| r.id == "get-and-body")
        .expect("get-and-body present in the pack");
    for phrase in [
        "vocabulary.generatedFileMarkers",
        "`exclude`",
        "machine-generated banner",
    ] {
        assert!(
            rule.message.contains(phrase),
            "egress/get-and-body's message no longer contains {phrase:?} -- the generated-file \
             exemption's limitation stopped being disclosed to the one person who would otherwise \
             wonder why their own banner is ignored"
        );
    }
}
