//! "This build is old" — the binary's self-report about its own age, and the ONLY update-notification
//! channel the manually installed Claude Desktop (`.mcpb`) lane has.
//!
//! ## The problem it exists for
//! A `.mcpb` distributed from GitHub Releases (ours) is not auto-updated by Claude Desktop — only
//! extensions listed in the official directory are — and our bundle carries no origin URL for a host to
//! poll even if it wanted to. MCP itself has no version-notification message (`serverInfo.version` is
//! the whole surface). So for that lane there is no delivery-layer notifier at all, the way the Claude
//! Code lane has a `SessionStart` hook. What is left is the binary saying what it knows about itself
//! — the shape the mcp-distribution decision settled on for exactly this gap.
//!
//! ## The two constraints, and the shape that satisfies both
//! 1. **No network.** "zzop sends your code nowhere" is a property anyone can check (`reqwest` appears
//!    zero times in this workspace), so this module reads one baked constant and the system clock and
//!    calls nothing. There is no HTTP here and there must never be — a version check is exactly the
//!    HTTPS-into-the-binary that the 2026-07-24 bootstrap decision rejected.
//! 2. **No over-claiming.** This module NEVER says a newer release exists. Without a network it cannot
//!    know that, and asserting it would be the failure `docs/`' output philosophy forbids. It states
//!    one fact it does know — its own source is N days old — and makes one RECOMMENDATION, "go look",
//!    which is a request for a human action rather than a claim about the world.
//!
//! ## Silence is the default, in every direction it can be
//! [`notice`] answers `None` when the stamp is absent (built off a git checkout with no
//! `SOURCE_DATE_EPOCH` — see `build.rs`), when the system clock predates the Unix epoch, when the clock
//! reads BEHIND the stamp (a skewed machine would otherwise be handed a negative age), and — the
//! ordinary case — when the source is younger than [`STALE_AFTER_DAYS`]. A channel that speaks on every
//! connection teaches its reader to skip it, and skipping it would cost this lane the one notification
//! it has.

// Generated by `build.rs`: `const SOURCE_COMMIT_EPOCH: Option<i64>` — the committer date, in Unix
// seconds, of the source `HEAD` this binary was built from, or `None` when the build could not learn
// it. `build.rs` owns why it is the SOURCE's date rather than the build's, and why baking it in this
// package (rather than in `crates/facade`) is what keeps `Cargo.lock` — and therefore every cache
// fingerprint — from moving. (A plain comment, not a doc comment: rustdoc does not attach one to a
// macro invocation and warns if you try.)
include!(concat!(env!("OUT_DIR"), "/build_stamp.rs"));

/// Where a reader goes after the notice. One owner: the serve-time stderr banner in
/// `src/bin/zzop-mcp.rs` prints the same string from here rather than repeating the literal.
pub const RELEASES_URL: &str = "https://github.com/eezz4/zzop/releases";

/// How old this binary's SOURCE must be before the notice speaks.
///
/// Set from the measured release cadence rather than from taste: across this project's first 27 days it
/// cut 30 releases and the LARGEST gap between two consecutive ones was 3 days. Ninety days is thirty
/// times that gap, so someone running the newest release cannot trip this notice even through a release
/// pause an order of magnitude longer than any that has happened. That direction is the one that
/// matters — a false "you are behind" on a current install is the fastest way to make the channel
/// ignorable, and this lane has no second channel to fall back on. It is still short enough to name an
/// install that is a full quarter and dozens of releases behind.
///
/// Deliberately NOT configurable. A knob here would let the one notification this lane has be switched
/// off, and nobody who wants it off is the person it is for.
const STALE_AFTER_DAYS: i64 = 90;

const SECONDS_PER_DAY: i64 = 86_400;

/// The notice for THIS binary, right now — `None` when there is nothing honest to say (the module doc
/// lists all four silences). Callers treat `None` as "print nothing", never as an empty string: the
/// stderr banner and MCP `initialize`'s `instructions` field both OMIT rather than emit blank.
pub fn notice() -> Option<String> {
    notice_at(SOURCE_COMMIT_EPOCH, now_epoch()?)
}

/// Wall clock as Unix seconds. `None` for a clock reading before 1970 (the one case `duration_since`
/// can fail) and for one too far past `i64` to represent — two more clock states that must not be
/// turned into a fabricated age.
fn now_epoch() -> Option<i64> {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()?
        .as_secs();
    i64::try_from(secs).ok()
}

/// The pure half, and the reason both inputs are arguments: every branch — including "no stamp at all"
/// and "the clock is behind the stamp" — is then reachable from a test without a build environment or a
/// machine that lies about the time. [`notice`] is the one-line impure wrapper over it.
///
/// A clock behind the stamp yields a negative or zero day count, which is below the threshold and
/// therefore silent by the same comparison that handles a fresh build; it needs no branch of its own.
fn notice_at(built: Option<i64>, now: i64) -> Option<String> {
    let days = now.checked_sub(built?)? / SECONDS_PER_DAY;
    if days < STALE_AFTER_DAYS {
        return None;
    }
    Some(format!(
        "This zzop-mcp build (version {version}) was made from source {days} days old. zzop makes no \
         network calls, so it cannot tell you whether a newer release exists — but a .mcpb bundle \
         installed from GitHub is never updated automatically. If you want the newest, see \
         {RELEASES_URL} and re-install.",
        version = crate::server::version(),
    ))
}

#[cfg(test)]
mod tests {
    use super::{notice_at, RELEASES_URL, SECONDS_PER_DAY, STALE_AFTER_DAYS};

    /// An arbitrary "now" — the pure function never reads the clock, so any value works and a fixed one
    /// keeps every case below reproducible.
    const NOW: i64 = 1_800_000_000;

    fn days_ago(days: i64) -> Option<i64> {
        Some(NOW - days * SECONDS_PER_DAY)
    }

    /// The positive lane: an old build says so, names how old, names which build it is, and points
    /// somewhere. Without this the module could be silent in every state and nothing would notice.
    #[test]
    fn an_old_build_reports_its_age_and_where_to_look() {
        let notice = notice_at(days_ago(200), NOW).expect("200 days must be reported");
        assert!(notice.contains("200 days old"), "got: {notice}");
        assert!(notice.contains(crate::server::version()), "got: {notice}");
        assert!(notice.contains(RELEASES_URL), "got: {notice}");
    }

    /// The negative lane, and the reason the positive one means anything: a current build says NOTHING.
    /// A notice that fires unconditionally is indistinguishable from a working one until someone
    /// upgrades and it keeps firing.
    #[test]
    fn a_current_build_is_silent() {
        assert_eq!(notice_at(days_ago(1), NOW), None);
        assert_eq!(notice_at(days_ago(0), NOW), None);
    }

    /// Pins the comparison DIRECTION at the boundary, which is the half of a threshold that silently
    /// inverts: one day under the threshold is silent, exactly the threshold speaks.
    #[test]
    fn the_threshold_boundary_is_inclusive() {
        assert_eq!(notice_at(days_ago(STALE_AFTER_DAYS - 1), NOW), None);
        assert!(notice_at(days_ago(STALE_AFTER_DAYS), NOW).is_some());
    }

    /// No stamp means no claim. A build off a source tarball (no `.git`, no `SOURCE_DATE_EPOCH`) knows
    /// nothing about its own age, and the honest output for "I do not know" is nothing at all — never a
    /// default age, which would be a fabricated fact wearing the shape of a measured one.
    #[test]
    fn an_absent_stamp_says_nothing() {
        assert_eq!(notice_at(None, NOW), None);
    }

    /// A machine whose clock sits behind the build's source date gets silence, not a negative age.
    /// Reachable in practice: a fresh install on hardware with a dead RTC reads some date in the past.
    #[test]
    fn a_clock_behind_the_stamp_says_nothing() {
        assert_eq!(notice_at(days_ago(-400), NOW), None);
    }

    /// The over-claim gate: the notice must never assert that a newer release EXISTS. It cannot know
    /// that without a network, and the whole design premise is that it never acquires one. This pins
    /// the disclaimer that makes the recommendation honest rather than an existence claim.
    #[test]
    fn the_notice_disclaims_knowing_whether_a_newer_release_exists() {
        let notice = notice_at(days_ago(365), NOW).expect("a year-old build must be reported");
        assert!(
            notice.contains("cannot tell you whether a newer release exists"),
            "got: {notice}"
        );
    }
}
