//! Derives every cache-invalidation fingerprint from the SOURCE that produces the cached bytes, so
//! nobody has to remember to bump one.
//!
//! ## What this replaces, and why the replacement is smaller than the thing replaced
//! Each fingerprint used to be a hand-held string (`"rust/syn-2/0.21.0"`, `CACHE_SCHEMA_VERSION`'s
//! `+rN`, `LEXICAL_FALLBACK_FINGERPRINT`, `DSL_INTERPRETER_FINGERPRINT`) that an author had to bump when
//! they changed the code behind it. A convention nobody can enforce needs a guard, the guard needs
//! escape hatches for the cases it reads wrong, and the hatches need their own rules — that stack was
//! ~400 lines of shell with three ways out, one of which left no record in history at all.
//!
//! A hash of the inputs needs none of it. It cannot be forgotten, it cannot be wrong in the dangerous
//! direction, and there is nothing to skip.
//!
//! ## The file set is DERIVED, never listed
//! Listing the files by hand would rebuild the same defect one layer down: a hand list inside a build
//! script is exactly as blind to a new file as a hand list inside a guard was. So the set comes from
//! Cargo: for a crate, hash every `.rs` under its own `src/`, then follow every `path = "..."`
//! dependency in its `Cargo.toml` and do the same, transitively. `parser-rust` declares `zzop-core` by
//! path, so `zzop-core`'s bytes are in `parser-rust`'s fingerprint because Cargo says they are — not
//! because someone wrote them down.
//!
//! ## Over-invalidation is accepted, on purpose
//! A comment-only edit moves the hash and wipes that language's cache. That is the asymmetry
//! `cache.md` records: over-invalidation costs recomputation, under-invalidation serves a WRONG ANSWER
//! from a stale entry. The scoping keeps the cost bounded — a change to `parser-go` does not touch the
//! TypeScript fingerprint, because Go is not in TypeScript's dependency closure.
//!
//! ## What is NOT derived
//! The human-readable id half of each fingerprint (`"rust/syn-2"`) stays hand-written in the parser
//! crate. It names the frontend and is what a person reads in a cache path or a bug report; it is not a
//! version and nothing depends on it moving.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/engine sits two levels under the workspace root")
        .to_path_buf();

    // (generated const name, crate dir relative to the workspace root). Every entry is a crate whose
    // SOURCE decides some cached byte; its dependency closure is walked from its own Cargo.toml.
    let targets: &[(&str, &str)] = &[
        ("FP_TYPESCRIPT", "parser/parser-typescript"),
        ("FP_PYTHON", "parser/parser-python-3"),
        ("FP_JAVA", "parser/parser-java-21"),
        ("FP_RUST", "parser/parser-rust"),
        ("FP_GO", "parser/parser-go"),
        ("FP_CSHARP", "parser/parser-csharp"),
        ("FP_SQL", "parser/parser-sql"),
        ("FP_PRISMA", "parser/parser-prisma"),
        // Not a parser: the schema rules crate. Its Rust logic reaches CACHED findings (the
        // `structural.rs` lane) with no pack content to hash, so it needs the same treatment — and it
        // used to carry a hand-held `STRUCTURAL_RULES_VERSION` for exactly that reason.
        ("FP_SCHEMA_RULES", "rules/native/rules-schema"),
    ];

    let mut out = String::from(
        "// Generated by build.rs — do not edit. Each value is a hash of the crate's own `src/**.rs`\n\
         // plus every `path = \"...\"` dependency's, transitively. See build.rs for why the set is\n\
         // derived from Cargo rather than listed.\n",
    );
    for (name, rel) in targets {
        let dir = workspace.join(rel);
        let hash = closure_fingerprint(&dir);
        out.push_str(&format!("const {name}: &str = \"{hash:016x}\";\n"));
    }
    // TWO MODULE-SCOPED tokens. Neither subject is a crate, so neither gets a dependency closure — and
    // that narrowness is the point rather than a shortcut. `crates/engine`'s own closure would have been
    // the easy answer for both, but it contains every parser crate by path, so a one-line Go edit would
    // move it — and it drives the BULK invalidator below, i.e. a full-cache wipe on every parser commit.
    // A token that broad stops distinguishing anything.
    //
    // The DSL interpreter's own semantics are what its token tracks; a change under `core/src/io/` must
    // not wipe every DSL findings entry.
    let dsl_hash = dir_fingerprint(&workspace.join("crates/core/src/dsl"));
    out.push_str(&format!("const FP_DSL: &str = \"{dsl_hash:016x}\";\n"));
    // The lexical fallback is `pipeline::lexical_loc` and the oversized/unrecognized branches that reach
    // it — all inside the engine's own pipeline module.
    let lexical_hash = dir_fingerprint(&workspace.join("crates/engine/src/pipeline"));
    out.push_str(&format!(
        "const FP_LEXICAL: &str = \"{lexical_hash:016x}\";\n"
    ));

    // The cache's bulk invalidator. Composed HERE rather than in a `concat!` at the use site: that macro
    // takes literals only, and half of this value is now computed. Both axes survive — the release
    // version (one cache generation reclaimed per release, see the const's own doc) and a source hash
    // that replaces the hand-held `+rN` counter.
    //
    // Its subject is the STORED SHAPE, so its input is the two crates that define what gets persisted:
    // `zzop-cache` (the entry envelopes) and `zzop-core` (`FileIrSlice`, `Finding`, and the shared types
    // they embed). Both by dependency closure, so a new file in either is covered the day it lands —
    // which is exactly what the hand list this replaces could never do.
    let mut schema_hash = FNV_OFFSET;
    for member in ["crates/cache", "crates/core"] {
        schema_hash = fnv_str(
            schema_hash,
            &format!("{:016x}", closure_fingerprint(&workspace.join(member))),
        );
    }
    let pkg_version = std::env::var("CARGO_PKG_VERSION").unwrap();
    out.push_str(&format!(
        "const CACHE_SCHEMA_VERSION_DERIVED: &str = \"{pkg_version}+{schema_hash:016x}\";\n"
    ));

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("fingerprints.rs");
    std::fs::write(&out_path, out).expect("write fingerprints.rs");
}

/// Hash of `crate_dir`'s own sources plus every path-dependency's, transitively. Cycles are impossible
/// in a Cargo dependency graph, but the visited set makes the walk terminate regardless and keeps a
/// diamond (two crates both depending on `zzop-core`) from hashing the same bytes twice.
fn closure_fingerprint(crate_dir: &Path) -> u64 {
    let mut visited: BTreeSet<PathBuf> = BTreeSet::new();
    let mut queue = vec![crate_dir.to_path_buf()];
    // Keyed by directory so the hash is independent of walk order — a BTreeMap gives one canonical
    // order for the same set of crates, which is what makes the build reproducible.
    let mut per_crate: BTreeMap<String, u64> = BTreeMap::new();
    while let Some(dir) = queue.pop() {
        let Ok(canonical) = dir.canonicalize() else {
            continue; // a path dependency that does not exist contributes nothing, never a panic
        };
        if !visited.insert(canonical.clone()) {
            continue;
        }
        per_crate.insert(
            canonical.to_string_lossy().replace('\\', "/"),
            dir_fingerprint(&dir.join("src")),
        );
        queue.extend(path_dependencies(&dir));
    }
    let mut h = FNV_OFFSET;
    for (name, hash) in &per_crate {
        // The crate's own path is hashed too: moving a crate changes its identity, and two crates whose
        // sources happen to hash equal must not collapse into one contribution.
        h = fnv_str(h, name.rsplit('/').next().unwrap_or(name));
        h = fnv_str(h, &format!("{hash:016x}"));
    }
    h
}

/// Content hash of every `.rs` file under `dir`, recursively, in sorted relative-path order. The path is
/// hashed alongside the bytes so a pure RENAME moves the fingerprint — a renamed module is a different
/// module to `mod`-tree resolution, and the earlier hand-list guard was measurably blind to exactly that.
fn dir_fingerprint(dir: &Path) -> u64 {
    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect_rs(dir, dir, &mut files);
    files.sort();
    let mut h = FNV_OFFSET;
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        h = fnv_str(h, rel);
        match std::fs::read(abs) {
            // Line endings are normalized so a CRLF/LF checkout difference cannot invalidate a cache
            // that is otherwise identical — this repo is CRLF on disk and LF in git.
            Ok(bytes) => h = fnv_bytes(h, &normalize_newlines(&bytes)),
            Err(_) => h = fnv_str(h, "<unreadable>"),
        }
    }
    h
}

fn collect_rs(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    println!("cargo:rerun-if-changed={}", dir.display());
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rs(base, &path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            let rel = path
                .strip_prefix(base)
                .unwrap_or(&path)
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}

/// Every `path = "..."` dependency directory declared in `crate_dir/Cargo.toml`, resolved against that
/// manifest's own directory. Line-based rather than a real TOML parse for the same reason
/// `pipeline::rust_workspace::parse_package_name` is: this workspace has no `toml` dependency, and a
/// build script is the last place to add one. The shape it must read is narrow and fixed — Cargo itself
/// only accepts `path = "..."` on one line of a dependency entry.
fn path_dependencies(crate_dir: &Path) -> Vec<PathBuf> {
    let manifest = crate_dir.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let Ok(text) = std::fs::read_to_string(&manifest) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for line in text.lines() {
        let Some(idx) = line.find("path") else {
            continue;
        };
        let after = line[idx + 4..].trim_start();
        let Some(after) = after.strip_prefix('=') else {
            continue;
        };
        let after = after.trim_start();
        let Some(rest) = after.strip_prefix('"') else {
            continue;
        };
        let Some(end) = rest.find('"') else { continue };
        let value = &rest[..end];
        // A `path` key naming a FILE is a build-target override (`[lib] path = "src/lib.rs"`), not a
        // dependency — skip it rather than hashing a directory that does not exist.
        if value.ends_with(".rs") {
            continue;
        }
        out.push(crate_dir.join(value));
    }
    out
}

/// LF-normalized bytes — see [`dir_fingerprint`]'s note on why.
fn normalize_newlines(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'\r' && bytes.get(i + 1) == Some(&b'\n') {
            i += 1;
            continue;
        }
        out.push(bytes[i]);
        i += 1;
    }
    out
}

// FNV-1a, 64-bit. Inlined rather than reused from `zzop-cache`'s own copy: making the cache crate a
// build-dependency of the engine would put it in the engine's build graph twice (host and target), and
// this is fifteen lines of a fully specified public algorithm. Not a cryptographic choice — the threat
// model is "did these bytes change", never "can someone forge a collision".
const FNV_OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

fn fnv_bytes(mut h: u64, bytes: &[u8]) -> u64 {
    for b in bytes {
        h ^= u64::from(*b);
        h = h.wrapping_mul(FNV_PRIME);
    }
    h
}

fn fnv_str(h: u64, s: &str) -> u64 {
    fnv_bytes(h, s.as_bytes())
}
