//! Detection of author-declared machine-generated files. A generated file (an OpenAPI/GraphQL client,
//! a protobuf stub, a router tree) is regenerated by its tool rather than hand-edited, so several
//! hygiene analyses (`dead-exports`, `dead-candidates`) treat a finding on one as non-actionable noise
//! and exempt it. Both consult this one detector so the exemption can't drift between them.

use std::path::Path;

/// Recognizes an explicit machine-generated banner in a file's head — the industry `@generated` /
/// "auto-generated" / "Code generated by … DO NOT EDIT." convention. Honoring it is safe (not a heuristic
/// guess): the marker is author-declared, and a generated file's exports/contents are regenerated rather
/// than hand-edited, so an "un-export the unused" / "delete this dead file" finding is non-actionable
/// there. Scoped to *comment* lines in the head so an incidental string literal in a hand-written file
/// can't trip it.
///
/// Every marker names *generation* explicitly — a bare "DO NOT EDIT" is deliberately NOT one (hand-written
/// headers like "do not edit — change via the admin UI" carry it; Go/protobuf's "Code generated by … DO
/// NOT EDIT." is caught by its `code generated by` half). Called only on TS-dispatched files (the callers
/// are TypeScript dead-code passes), so the accepted comment prefixes are TS's — `//`, `/*`, `*`
/// (block-comment continuation, e.g. ` * @generated`); `#` is excluded (in TS it opens a private field,
/// live code).
pub(crate) fn has_generated_banner(text: &str) -> bool {
    // Substrings sought inside a head comment, matched case-insensitively. Each is either the `@generated`
    // tag, a tool name, or a *subject-anchored* generation phrase ("code generated by", "this file
    // was/is generated") — never a bare verb-phrase like "generated by"/"generated from", which occurs in
    // ordinary head prose ("token generated by the auth server", "generated by hand from the spec") and
    // would wrongly exempt a hand-written file. swagger-typescript-api's "THIS FILE WAS GENERATED VIA …"
    // banner is caught by the subject-anchored "this file was generated" half, not a bare "generated via".
    const MARKERS: &[&str] = &[
        "@generated",
        "auto-generated",
        "autogenerated",
        "automatically generated",
        "code generated by", // Go/protobuf: "// Code generated <tool> DO NOT EDIT."
        "this file is generated",
        "this file was generated", // swagger-typescript-api: "THIS FILE WAS GENERATED VIA …"
        "openapi-generator",
    ];
    text.lines()
        .take(8)
        .filter_map(|line| {
            let t = line.trim_start();
            // A generated banner is always a header comment, never live code — require a TS comment prefix.
            let body = t
                .strip_prefix("//")
                .or_else(|| t.strip_prefix("/*"))
                .or_else(|| t.strip_prefix('*'))?;
            Some(body.to_ascii_lowercase())
        })
        .any(|line| MARKERS.iter().any(|m| line.contains(m)))
}

/// True when the file at `root/rel` opens with a machine-generated banner ([`has_generated_banner`]).
/// The `dead-candidates` post-filter uses it to stay consistent with `dead-exports`: a generated file is
/// non-actionable for both (regenerated, not hand-edited), so flagging the file as "dead" right after we
/// stop flagging its exports would just read as noise. Reads the file head; false on an unreadable file.
pub(crate) fn file_has_generated_banner(root: &Path, rel: &str) -> bool {
    match std::fs::read(root.join(rel)) {
        Ok(bytes) => has_generated_banner(&String::from_utf8_lossy(&bytes)),
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::has_generated_banner;

    #[test]
    fn recognizes_common_generated_banners() {
        // hey-api / openapi-ts (the be-fastapi-fs corpus case that motivated this)
        assert!(has_generated_banner(
            "// This file is auto-generated by @hey-api/openapi-ts\nexport const x = 1;\n"
        ));
        // Meta/Phabricator canonical marker inside a block comment
        assert!(has_generated_banner(
            "/* @generated */\nexport const y = 2;\n"
        ));
        // Go/protobuf convention — caught by the `code generated by` half, not a bare "DO NOT EDIT"
        assert!(has_generated_banner(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n"
        ));
        // Block-comment continuation line (the `*` prefix path), marker not on the opening `/*` line
        assert!(has_generated_banner(
            "/*\n * @generated by some-tool\n */\nexport const z = 3;\n"
        ));
        // Banner a few rows down, not on line 1 (the TanStack routeTree.gen.ts shape)
        assert!(has_generated_banner(
            "/* eslint-disable */\n\n// @ts-nocheck\n\n// This file was automatically generated by a tool.\n"
        ));
        // swagger-typescript-api banner (the fe-vue corpus case) — on a block-comment continuation line,
        // no "auto-generated"/"@generated". Caught by the subject-anchored "this file was generated" half
        // of "THIS FILE WAS GENERATED VIA …", NOT a bare "generated via" (which we deliberately don't match).
        assert!(has_generated_banner(
            "/* eslint-disable */\n/* tslint:disable */\n// @ts-nocheck\n/*\n * ## THIS FILE WAS GENERATED VIA SWAGGER-TYPESCRIPT-API ##\n */\nexport class Api {}\n"
        ));
    }

    #[test]
    fn does_not_flag_ordinary_source() {
        assert!(!has_generated_banner(
            "import axios from 'axios';\nexport const request = () => {};\n"
        ));
        // A comment that merely mentions editing, without a generated marker
        assert!(!has_generated_banner(
            "// edit this config to taste\nexport const config = {};\n"
        ));
        // The marker as a bare string literal in live code (not a comment) must not match
        assert!(!has_generated_banner(
            "export const msg = 'do not edit the database directly';\n"
        ));
        // A bare "DO NOT EDIT" header on a hand-written file must NOT be treated as generated — the
        // false-clear surface: it names no generation, and human headers ("change via the admin UI")
        // carry it. Only "Code generated by … DO NOT EDIT." qualifies, via its `code generated by` half.
        assert!(!has_generated_banner(
            "// Config module. DO NOT EDIT directly — change it via the admin UI.\nexport const cfg = {};\n"
        ));
        // A TS private class field whose name contains a marker substring must NOT exempt the file —
        // `#` opens live code in TS, not a comment.
        assert!(!has_generated_banner(
            "class C {\n  #autogeneratedId = 1;\n}\nexport const c = new C();\n"
        ));
        // Bare verb-phrases ("generated by hand", "generated from …") in ordinary head prose must NOT
        // exempt a hand-written file — the reason MARKERS uses subject-anchored phrases, not bare
        // "generated by/from". Guards against anyone re-adding the loose form.
        assert!(!has_generated_banner(
            "// Types generated by hand from the OpenAPI spec — keep in sync.\nexport type T = number;\n"
        ));
        assert!(!has_generated_banner(
            "// Wraps the token generated by the auth server.\nexport const wrap = () => {};\n"
        ));
        // A marker buried far below the head is ignored
        let mut deep = String::new();
        for _ in 0..20 {
            deep.push_str("export const a = 1;\n");
        }
        deep.push_str("// @generated\n");
        assert!(!has_generated_banner(&deep));
    }
}
