//! The public input/output types of [`super::find_dead_exports`] — their own file because the module
//! head sits at the repo's 300-line ceiling and these are pure declaration. Re-exported by the parent,
//! so the crate's public path is unchanged.

use std::collections::HashSet;

use serde::{Deserialize, Serialize};

use zzop_core::{ImportMap, ReExport, SourceSymbolKind};

/// One exported symbol a file offers as a dead-export candidate.
#[derive(Debug, Clone)]
pub struct DeadExportCandidate {
    pub name: String,
    pub kind: SourceSymbolKind,
    /// `export default function Foo() {}` — also matchable via the file's `#default` import key.
    pub is_default: bool,
}

/// One file's contribution to `find_dead_exports`.
#[derive(Debug, Clone, Default)]
pub struct DeadExportInputFile {
    pub file: String,
    pub exports: Vec<DeadExportCandidate>,
    pub imports: ImportMap,
    /// `export { X } from "./a"` / `export * from "./a"`.
    pub re_exports: Vec<ReExport>,
    /// `import("./a")` dynamic-import specifiers.
    pub dynamic_imports: Vec<String>,
    /// Identifier names referenced anywhere in the file (see module doc's `used_names` paragraph).
    pub used_names: HashSet<String>,
    /// Names appearing in the PUBLIC SIGNATURE of some exported declaration in this file — the
    /// position-aware companion `used_names` cannot be. Drives the public-signature exemption (see
    /// module doc). Empty for a parser that does not produce it, which simply means no exemptions.
    pub exported_signature_names: HashSet<String>,
    /// Local export RENAMES — `(local declaration name, public export name)` for every from-less
    /// `export { X as Y }` in this file (`zzop_parser_typescript::parse_dead_export_facts`). An
    /// export candidate is named by its DECLARATION (`X`), but an importer's key is the PUBLIC name
    /// (`Y`); this is the only place those two meet. NOT a liveness grant on its own — a rename
    /// nobody imports leaves the export dead, exactly as before (see `find_dead_exports`).
    /// Empty for a parser that does not produce it, which simply restores the pre-existing behavior.
    pub export_aliases: Vec<(String, String)>,
    /// The engine detected an author-declared machine-generated banner in this file's head —
    /// `@generated`, "auto-generated", "Code generated by … DO NOT EDIT.", and friends. NOT a bare
    /// "DO NOT EDIT": `crates/engine/src/generated_banner.rs` deliberately refuses that one (a
    /// hand-written "DO NOT EDIT directly — change it via the admin UI" header carries it) and pins the
    /// refusal with its own test. This doc used to spell the pair `@generated`/"DO NOT EDIT", which
    /// advertised an exemption the detector does not grant.
    /// When set, the file's exports are skipped whole (its imports still count) — see module doc.
    pub is_generated: bool,
    /// Export names of THIS file that some OTHER file writes as a BARE IDENTIFIER, resolved through a
    /// build-time auto-import table rather than any import statement (see module doc). Supplied by the
    /// engine (`nuxt_auto_import::scan`), which owns the anchor and the per-app scope wall; this crate
    /// never decides which directories a framework injects. Empty for every tree and file the engine
    /// resolved nothing for, which restores the previous behavior exactly.
    pub auto_import_referenced_names: HashSet<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum DeadExportReason {
    /// Never referenced anywhere — a deletion candidate.
    Unused,
    /// Referenced only within its own file — an un-export candidate.
    InFileOnly,
}

/// One dead-export finding, with no line number attached — a caller looks one up by `(file, name)`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeadExport {
    pub file: String,
    pub name: String,
    pub kind: SourceSymbolKind,
    pub reason: DeadExportReason,
}
