//! The generated-file exemption shared by `no-explicit-any` and `as-cast`: both carry the same
//! `LineScan::require_file_absent` banner regex, so a file the author declared machine-generated goes
//! silent for both. The rules' fix advice is "change this line", which nobody can follow in a file the
//! next `openapi-ts`/`tanstack-router` run overwrites -- measured on the dogfood corpus at 30 findings
//! across `fe-vue/src/services/api.ts` (12) and `be-fastapi-fs/frontend/src/routeTree.gen.ts` (18).
//!
//! ## What these tests pin, and why each case exists
//! The regex deliberately mirrors `zzop_engine::generated_banner`'s detector rather than merely
//! containing the marker words, because the two layers answer the SAME question about the SAME file and
//! a divergence between them is invisible: `unimported-export` would call a file generated while
//! `as-cast` did not. So the head window (8 lines) and the comment-prefix requirement are both pinned
//! here, in both directions -- a marker one line past the window, and a marker in a head STRING
//! literal, must each still fire. A loose "marker anywhere in the file" spelling passes every
//! suppression case below and fails all three live-file cases; that is the whole point of having them.
//!
//! ## The disclosure, pinned as a test
//! `vocabulary.generatedFileMarkers` does NOT reach these rules -- a matcher's patterns are compiled
//! from the pack JSON and `zzop-core`'s DSL layer is vocabulary-free by construction. A house generator
//! stamping its own banner -- or stamping none at all -- is still flagged, and the answer in either case
//! is `exclude`. That limitation is
//! stated in both rules' `message`, and `disclosure_survives_in_both_messages` below is what stops a
//! future message rewrite from dropping it silently.

use super::*;

/// The two rules that share the exemption, as their bare ids.
const EXEMPTED_RULES: [&str; 2] = ["no-explicit-any", "as-cast"];

/// Every fixture body below is the same two offending lines, so a count is directly comparable across
/// cases: one `as any` (fires BOTH rules on that line) and one `: any` (fires `no-explicit-any` only).
const OFFENDING_BODY: &str = "export const a = {} as any;\nlet b: any = 1;\nexport const bb = b;\n";

fn counts(files: &[(&str, &str)]) -> Vec<(&'static str, usize)> {
    EXEMPTED_RULES
        .iter()
        .map(|r| (*r, rule_findings(files, r).len()))
        .collect()
}

/// A head banner silences both rules WHOLE-FILE -- and the same run's un-bannered sibling still fires,
/// so a zero here cannot be the fixture, the pack load, or the analyzer having done nothing.
#[test]
fn head_banner_silences_both_rules_while_a_sibling_still_fires() {
    let bannered = format!("// @generated by acme-codegen\n{OFFENDING_BODY}");
    let plain = format!("// hand-written, no banner\n{OFFENDING_BODY}");
    let files = [
        ("src/gen.ts", bannered.as_str()),
        ("src/hand.ts", plain.as_str()),
    ];
    for rule in EXEMPTED_RULES {
        let hits = rule_findings(&files, rule);
        let gen_hits: Vec<_> = hits.iter().filter(|f| f.file.ends_with("gen.ts")).collect();
        let hand_hits: Vec<_> = hits
            .iter()
            .filter(|f| f.file.ends_with("hand.ts"))
            .collect();
        assert!(
            gen_hits.is_empty(),
            "typescript/{rule} fired on the bannered file: {gen_hits:?}"
        );
        assert!(
            !hand_hits.is_empty(),
            "typescript/{rule} fired on NEITHER file -- the control is silent too, so the \
             suppression above proves nothing"
        );
    }
}

/// The engine's `MARKERS` list, READ FROM ITS SOURCE BYTES rather than re-typed here.
///
/// `zzop_engine::generated_banner::MARKERS` is `pub(crate)`, so this crate cannot import it — and a
/// hand-copied list is exactly the failure this whole module exists to prevent: add a ninth spelling
/// to the engine and a re-typed list stays green while the two layers start disagreeing about which
/// files are generated. Reading the other side's bytes is this repo's established answer when a
/// boundary admits no shared symbol (`rules-http`'s `MARKER_WINDOW_PROSE_PAGES` and the engine's own
/// `surface_parity` source-scrape do the same).
///
/// The floor matters: if the const is renamed or reshaped, the extraction yields nothing, and an
/// empty list would make the loop below pass vacuously. So an implausibly small result is a failure.
fn engine_marker_spellings() -> Vec<String> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        // `CARGO_MANIFEST_DIR` is the CRATE root (`rules/`), not this file's directory.
        .join("../crates/engine/src/generated_banner.rs");
    let src = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let body = src
        .split_once("const MARKERS: &[&str] = &[")
        .unwrap_or_else(|| {
            panic!("generated_banner.rs no longer declares `MARKERS` in the shape this pin reads")
        })
        .1;
    let body = body
        .split_once("];")
        .expect("the MARKERS literal is unterminated")
        .0;
    let markers: Vec<String> = body
        .lines()
        .filter_map(|l| l.trim().strip_prefix('"'))
        .filter_map(|l| l.split_once('"').map(|(m, _)| m.to_string()))
        .collect();
    assert!(
        markers.len() >= 5,
        "extracted only {} marker spellings from generated_banner.rs -- the const's shape changed and \
         this pin is now reading almost nothing. An empty list would silence every case below.",
        markers.len()
    );
    markers
}

/// Every banner spelling the engine recognizes must silence these rules too, or the two layers
/// disagree about which files are generated. The spellings come from `engine_marker_spellings()`;
/// the extra heads below are SHAPES, not vocabulary — the real corpus banners in their real casing
/// and comment styles (swagger-typescript-api's uppercase block-comment continuation, and the
/// routeTree.gen.ts preamble that pushes the banner down to line 7).
#[test]
fn every_engine_marker_spelling_is_honored() {
    let mut heads: Vec<String> = engine_marker_spellings()
        .iter()
        .map(|m| format!("// {m}"))
        .collect();
    heads.extend(
        [
            "// This file is auto-generated by @hey-api/openapi-ts",
            "// This file was automatically generated by TanStack Router.",
            "// Code generated by protoc-gen-go. DO NOT EDIT.",
            "/*\n * ## THIS FILE WAS GENERATED VIA SWAGGER-TYPESCRIPT-API ##\n */",
            // Not on line 1, and behind the eslint/ts-nocheck preamble every generator emits -- the
            // routeTree.gen.ts shape, where the banner lands on line 7.
            "/* eslint-disable */\n\n// @ts-nocheck\n\n// noinspection JSUnusedGlobalSymbols\n\n// @generated",
        ]
        .map(String::from),
    );
    for head in heads {
        let src = format!("{head}\n{OFFENDING_BODY}");
        let files = [("src/gen.ts", src.as_str())];
        assert_eq!(
            counts(&files),
            vec![("no-explicit-any", 0), ("as-cast", 0)],
            "banner head not honored:\n{head}"
        );
    }
}

/// The head window is 8 LINES, the same as the engine detector's. Pinned on both sides of the edge so
/// widening it to the whole file (which would silence a hand-written file that merely mentions a
/// generator in a comment) fails here rather than in a user's silent report.
#[test]
fn the_head_window_ends_at_line_eight() {
    let filler = "// 1\n// 2\n// 3\n// 4\n// 5\n// 6\n";
    let on_line_eight = format!("{filler}// 7\n// @generated\n{OFFENDING_BODY}");
    let on_line_nine = format!("{filler}// 7\n// 8\n// @generated\n{OFFENDING_BODY}");

    let inside = [("src/gen.ts", on_line_eight.as_str())];
    assert_eq!(
        counts(&inside),
        vec![("no-explicit-any", 0), ("as-cast", 0)],
        "a banner on line 8 is inside the head window and must silence both rules"
    );

    let outside = [("src/late.ts", on_line_nine.as_str())];
    assert_eq!(
        counts(&outside),
        vec![("no-explicit-any", 2), ("as-cast", 1)],
        "a banner on line 9 is PAST the head window -- the file is hand-written as far as this \
         exemption is concerned and both rules must still fire"
    );
}

/// A marker must be in a COMMENT, exactly as the engine detector requires. The two live-code shapes
/// that carry marker words in real trees are a string literal (a codegen tool written in TypeScript
/// has its own banner as a template) and a TS private field, whose `#` opens live code.
#[test]
fn a_marker_outside_a_head_comment_does_not_exempt() {
    let in_string =
        format!("export const banner = \"// @generated by our codegen\";\n{OFFENDING_BODY}");
    let in_field = format!("class C {{\n  #autogeneratedId = 1;\n}}\n{OFFENDING_BODY}");
    // Marker on line 12, well past the 8-line head window: the shape of a hand-written file that
    // merely mentions a generator somewhere in its own body.
    let filler = "export const p1 = 1;\nexport const p2 = 2;\nexport const p3 = 3;\nexport const p4 = 4;\nexport const p5 = 5;\nexport const p6 = 6;\nexport const p7 = 7;\nexport const p8 = 8;\nexport const p9 = 9;\n";
    let deep = format!(
        "// ordinary header\n{filler}// auto-generated section below, keep in sync\n{OFFENDING_BODY}"
    );

    for (label, src, expected) in [
        (
            "head string literal",
            in_string.as_str(),
            vec![("no-explicit-any", 2), ("as-cast", 1)],
        ),
        (
            "TS private field",
            in_field.as_str(),
            vec![("no-explicit-any", 2), ("as-cast", 1)],
        ),
        (
            "comment below the head",
            deep.as_str(),
            vec![("no-explicit-any", 2), ("as-cast", 1)],
        ),
    ] {
        let files = [("src/live.ts", src)];
        assert_eq!(counts(&files), expected, "{label}: file must stay live");
    }
}

/// The exemption's own honesty check. `vocabulary.generatedFileMarkers` is a real config key that the
/// engine's dead-code analyses read and these rules CANNOT (a DSL matcher compiles its patterns from
/// the pack JSON, with no vocabulary input), so a project whose house generator stamps a different
/// banner still gets flagged here. Silence about that reaches the user AS silence, which is why it is
/// in the shipped message and why this test refuses a message that stops saying it.
#[test]
fn disclosure_survives_in_both_messages() {
    let pack = typescript_pack();
    for rule_id in EXEMPTED_RULES {
        let rule = pack
            .rules
            .iter()
            .find(|r| r.id == rule_id)
            .unwrap_or_else(|| panic!("{rule_id} present in the pack"));
        for phrase in [
            "vocabulary.generatedFileMarkers",
            "`exclude`",
            "machine-generated banner",
        ] {
            assert!(
                rule.message.contains(phrase),
                "typescript/{rule_id}'s message no longer contains {phrase:?} -- the \
                 generated-file exemption's limitation stopped being disclosed to the one person who \
                 would otherwise wonder why their own banner is ignored"
            );
        }
    }
}
